### ISSUE TITLE
Getting Started - Using this Component in a Webpack Prj

### ISSUE THREAD

**Issue by spottedmahn** [ovsleep/bootstrap-switch#2]
I'm trying to use this component in a webpack prj and webpack is complaining it can't find the module.  I cloned the sample and it works great but it is using systemjs.  Is there an example using webpack?  Thanks.

**Comment by ovsleep** [comment]
Hi, sorry, but I'm not very familiar with webpack. Although, If i'm not wrong angular-cli uses webpack instead of systemjs. And I just get a pull request to make this component compatible with angular-cli. Didn't have the time to test it yet, but maybe you can give it a try: [https://github.com/ovsleep/bootstrap-switch/pull/1](url)

**Comment by ovsleep** [comment]
Did this worked for you @spottedmahn ? Let me know so I can close this issue or assist you further.

**Comment by spottedmahn** [comment]
@ovsleep sorry, I haven't had time to circle back.  Let me give it a try **today**.
